charts:
  - name: loki
    namespace: loki
    repo: https://grafana.github.io/helm-charts
    chart: loki-stack
    valuesPath: "loki/values.yaml"

  - name: kube-state-metrics
    namespace: kube-system
    repo: https://prometheus-community.github.io/helm-charts
    chart: kube-state-metrics

  - name: metallb
    namespace: metallb
    repo: https://metallb.github.io/metallb
    chart: metallb
    valuesPath: "metallb/values.yaml"

  - name: cert-manager
    namespace: cert-manager
    repo: https://charts.jetstack.io
    chart: cert-manager
    valuesPath: "cert-manager/values.yaml"

  - name: ingress-nginx
    namespace: ingress
    repo: https://kubernetes.github.io/ingress-nginx
    chart: ingress-nginx
    depends:
      - metallb # these are currently unsupported, but this works anyways b/c pulumi waits long enough for everything to be ready
